'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("WinTeamTweak.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property _7zFM32() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_7zFM32", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property _7zFM64() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("_7zFM64", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property NSudoLG32() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NSudoLG32", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Byte[] 类型的本地化资源。
        '''</summary>
        Friend ReadOnly Property NSudoLG64() As Byte()
            Get
                Dim obj As Object = ResourceManager.GetObject("NSudoLG64", resourceCulture)
                Return CType(obj,Byte())
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Windows Registry Editor Version 5.00
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Policies]
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft]
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\AdtAgent]
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\AdtAgent\Parameters]
        '''&quot;EventlogLoggingLevel&quot;=dword:00000002
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Cryptography]
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Cryptography\Configuration]
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Cryptography\C [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property PoliciesHKLM22000() As String
            Get
                Return ResourceManager.GetString("PoliciesHKLM22000", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 Windows Registry Editor Version 5.00
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\RegisteredApplications]
        '''&quot;File Explorer&quot;=&quot;SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Capabilities&quot;
        '''&quot;Notepad&quot;=&quot;Software\\Microsoft\\Windows\\Notepad\\Capabilities&quot;
        '''&quot;Microsoft Edge&quot;=&quot;Software\\Clients\\StartMenuInternet\\Microsoft Edge\\Capabilities&quot;
        '''
        '''[HKEY_LOCAL_MACHINE\SOFTWARE\Clients\StartMenuInternet\Microsoft Edge\Capabilities]
        '''&quot;ApplicationDescription&quot;=&quot;Microsoft Edge 是以闪电速度运行网页和应用程序的 Web 浏览器。它快速、稳定而且易于使用。通过 Microsoft [字符串的其余部分被截断]&quot;; 的本地化字符串。
        '''</summary>
        Friend ReadOnly Property RegisteredApplications() As String
            Get
                Return ResourceManager.GetString("RegisteredApplications", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
